### ISSUE TITLE
c#代码块没有高亮关键字

### ISSUE THREAD

**Issue by YlyAyzbl** [flyun/chatAir#1]
发现个bug 
询问gpt c#代码 他写的代码块没有高亮
软件版本是1.0.2 
![Screenshot_2024-01-23-11-50-10-577_info flyun chatair](https://github.com/flyun/chatAir/assets/63178854/a720ebff-272f-4993-a7d3-144f73ea0727)

**Comment by flyun** [comment]
1.0.3版本已经解决
