### ISSUE TITLE
不知道是不是bug，抑或是我姿势不对

### ISSUE THREAD

**Issue by Lianjiangwuli** [flyun/chatAir#10]
有时长时间不对话，重新对话要清除上下文，要不然就显示出错。期待大佬能继续更新，挺喜欢这个项目！

**Comment by Lianjiangwuli** [comment]
还有个疑似bug，对话时ai输出过程中如果返回退出聊天界面，ai就停止输出了！然后继续对话就开始报错，又得清除上下文了。

**Comment by flyun** [comment]
> 有时长时间不对话，重新对话要清除上下文，要不然就显示出错。期待大佬能继续更新，挺喜欢这个项目！

可以贴一下这种情况下的错误提示截图吗

**Comment by flyun** [comment]
> 还有个疑似bug，对话时ai输出过程中如果返回退出聊天界面，ai就停止输出了！然后继续对话就开始报错，又得清除上下文了。

输出过程中返回聊天界面就会停止输出，确实就是这样处理的。因为会涉及到多个聊天窗口同时输出，处理这种情况会产生更多问题，所以就暂时这样处理。

至于你说的这种情况出错可以贴一下错误提示截图吗？
如果使用Gemini模型，必须一问一答才可以正常对话（Google的魔幻操作）。猜测退出聊天界面时，并没有回答。导致下一次聊天出现错误问题。

**Comment by Lianjiangwuli** [comment]
> > 还有个疑似bug，对话时ai输出过程中如果返回退出聊天界面，ai就停止输出了！然后继续对话就开始报错，又得弄清楚上下文了。
> 
> 因为会涉及到多个聊天窗口会同时输出，处理这种情况产生更多问题，所以就暂时这样处理。
> 
> 至于你说的这种情况错误可以贴一下错误提示截图吗？ 如果使用双子座模型，必须一问一答才可以正常对话（Google的魔幻操作）。猜测退出聊天界面时，并没有回答。导致下一次聊天出现错误问题。

是gemini，退出聊天界面就不回答了，下次聊就出现错误

**Comment by Lianjiangwuli** [comment]
> > 有时长时间不对话，重新对话要清理上下文，要不然就显示错误。期待大佬能继续更新，挺喜欢这个项目！
> 
> 可以贴一下这种情况的错误提示截图吗

![IMG_20240227_225904](https://github.com/flyun/chatAir/assets/43761112/6f39d9db-e35d-43f0-9fa3-4cd37dea8265)
这个是gemini聊天生成时退出聊天界面后，再次聊天出错的图，长时间不对话出错的我暂时没复现。
