### ISSUE TITLE
大佬有打算跟进gemini 1.5的调用吗？

### ISSUE THREAD

**Issue by Lianjiangwuli** [flyun/chatAir#12]
如题，现在1.5开放调用API 了

**Comment by flyun** [comment]
看下这个文档
https://ai.google.dev/models/gemini?hl=zh-cn
现在Gemini 1.5只是提供了预览版，只能在Google的aistudio去测试使用
Aistudio地址在下面
https://aistudio.google.com/app/prompts/new_chat

如果gemini-1.5-pro支持api后，会第一时间更新。也自己在聊天界面，点击头像，ai模型，选择自定义模型，在列表中选择自定义模型，填入gemini-1.5-pro-latest保存使用。
