### ISSUE TITLE
ChatGPT发布免登录的畅想

### ISSUE THREAD

**Issue by topkof** [flyun/chatAir#14]
chatgpt免登陆使用了，是否可以增加非api方式进行对话

**Comment by flyun** [comment]
确实考虑过，之前有潘多拉的项目，因为涉及到损害openai的利益，风控越来越严格，作者投入精力越来越大，最终停止维护维护。
如果你确实有这方面需求，可以考虑看看下面这个项目，免登陆输出api。服务器搭建，客户端改下地址就可以使用。
https://github.com/aurora-develop/aurora

如果后续openai允许免登陆转发api这种方式，也会集成到客户端，就不需要自己搭建服务器转发api

**Comment by topkof** [comment]
> 确实考虑过，之前有潘多拉的项目，因为涉及到损害openai的利益，风控越来越严格，作者投入精力越来越大，最终停止维护维护。
> 如果你确实有这方面需求，可以考虑看看下面这个项目，免登陆输出api。服务器搭建，客户端改下地址就可以使用。
> https://github.com/aurora-develop/aurora
> 
> 如果后续openai允许免登陆转发api这种方式，也会集成到客户端，就不需要自己搭建服务器转发api
> 

感谢您的回复！
