### ISSUE TITLE
麻烦增加 Gemini 1.5 Flash 模型

### ISSUE THREAD

**Issue by juneix** [flyun/chatAir#16]
首先感谢开发者提供的这个小工具，非常方便，操作也很流畅。

Google AI Studio 出新的 Gemini 1.5 Flash 模型了，辛苦作者更新一下。
`gemini-1.5-flash-latest`

我在【API 服务器设置】里添加了一个 one-API 的服务器，然后新建对话选择【自定义模型】添加`gemini-1.5-flash-latest`后，好像默认会匹配到这里，导致【Gemini API Server】未生效。

<img width="368" alt="HapiGo 2024-05-18 11 10 42" src="https://github.com/flyun/chatAir/assets/81808039/97fd1a86-8f41-4846-a1ea-a49011883150">

**Comment by flyun** [comment]
Gemini 1.5 Flash模型已经支持，下载1.0.6版本后，配置好Gemini API Key，选择Gemini 1.5 Flash模型就可以使用。

如果要配置one-API，正确的操作是在【API服务器设置】-【API服务器】进行配置。

关于你说配置Gemini API Server失效的问题，他对应的协议是Gemini类型。而one-API对应的协议是OpenAI类型，对应的是API服务器，并不是Gemini API Server。

这里后续会优化，即使不特别说明，也让用户更容易明白在哪里应该填什么。
