### ISSUE TITLE
可以给自定义模型添加上传图片的支持吗

### ISSUE THREAD

**Issue by XMWML** [flyun/chatAir#17]
gpt-4o列表里没有但是支持上传图片，可以给自定义模型名称但是也加上上传图片的支持

**Comment by flyun** [comment]
下载1.0.6版本，选择GPT-4o (Picture model)模型，就可以上传图片。

现在是临时处理的方案，GPT-4o发送文本或图片，需要切换对应模型，分别是GPT-4o与GPT-4o (Picture model)，但本质上都是gpt-4o这个模型。文档我还没看，估计可以文字图片可以一起作为上下文。如果是这样，之后会改为选择gpt-4o后，不需要切换模型，就可以发送图片以及文字。

最近一段时间比较忙，再加上正在做适配Claude模型与重新设计API服务商配置的计划，所以先临时这样处理，后续会改为更人性化方案。
