### ISSUE TITLE
非常优秀的项目

### ISSUE THREAD

**Issue by muhanstudio** [flyun/chatAir#19]
这个项目太好用了，尤其是这个基于电报的UI，只是还缺少关注度，作者加油，如果可以留个联系方式让我们捐赠开发就好了，金额虽小也是心意

另外，目前使用也遇到了以下这些问题：

1. 自定义模型不能上传图片
2. 无法自动读取中转api支持的模型(参考 https://github.com/open-webui/open-webui 项目请求 
'https://api.xxxx/v1/models' 来查询所有支持的模型)
![1718563209588](https://github.com/flyun/chatAir/assets/29907393/2b89695b-32f9-4f21-a952-ff20ccd56eec)

4. 如果作者还有精力的话，希望增加更多的代码渲染功能，例如mermaid，echart，flowchart等等（目前很多web端项目都支持渲染）
渲染效果：
![image](https://github.com/flyun/chatAir/assets/29907393/8930d685-197f-4be9-88da-e549f77272a1)
实际代码：
![image](https://github.com/flyun/chatAir/assets/29907393/e7759bdd-0bfc-45ac-90cc-598f35d4db00)

**Comment by flyun** [comment]
1.自定义模型上传图片的问题，正在开发，马上就可以支持。
2.中转api支持的模型打算放到自定义模型那个地方，读取支持的模型，可以点击模型自动添加到自定义模型列表。
3.markdown高级语法，数学公式、时序图等等任务图也会支持的。因为前端有丰富的开源库支持markdown语法，方便集成。客户端则需要自己二次开发开源库，加上telegram特殊的文字渲染机制导致集成麻烦，所以这也是telegram到现在也不支持markdown的原因。

感谢支持ChatAIr，如果有什么需要帮忙的地方，请推荐给更多人使用，或者提出反馈意见与新版本的bug。

ChatAir开发的目的，借助telegram基础上，给Android用户带来流畅轻巧的使用体验。虽然有很多同类型前端、flutter、rn编译的Android应用，但毕竟不是原生应用。ChatAIr在低端机也能流畅运行，让AI真正能帮助更多的人。我也一直以流畅不卡顿为标准进行开发，加上个人精力有限，所以一些功能开发不及时，这可能也是关注度不足。但也会持续更新，不断完善下去。
