### ISSUE TITLE
增加标题隐藏功能

### ISSUE THREAD

**Issue by libukai** [flyun/chatAir#23]
非常感谢作者开发了这个项目，找了很久类似的产品，这个是完成度最高最好用的了，👍🏻

我使用的设备是有道超级词典，可以理解为一个带有小键盘的横屏设备。因此在使用的过程中，受屏幕尺寸的限制，对于显示空间非常敏感。希望作者可以考虑增加一个标题隐藏的开关，在对话进行的过程中，自动隐藏标题，让屏幕的利用率最大化。

![IMG_6221](https://github.com/flyun/chatAir/assets/5654585/4756b4cd-8d8f-4248-8879-7f8ff1660197)

**Comment by flyun** [comment]
标题隐藏功能，如果实现最简单的方式，就直接在选项里配置隐藏标题栏，让标题栏一直不显示。
如果考虑到标题栏自动隐藏和显示，受限于设备（不清楚这个设备是否可以触摸），隐藏后再显示标题栏对于不同的设备处理起来会很麻烦。

隐藏标题栏我先简单实现下，后续在优化体验。

**Comment by libukai** [comment]
好的，非常感谢，隐藏标题栏就可以满足需求了

**Comment by libukai** [comment]
你好，请问一下，最近的一版好像还没有实现这个功能吧？看了一下升级文档和配置好像都还没有

**Comment by flyun** [comment]
是的，如果更新日志没提到就没实现这个功能。
预计下周发版添加上这个功能，上个版本简单隐藏了下，发现需要做下UI上的兼容，比如顶上的黑条变成主题色，又或者聊天列表在黑条下面，又或者背景填充整个页面隐藏状态栏内容。
![FEF287D2-4B4A-4F7B-BDF1-B9CF85983990-min](https://github.com/user-attachments/assets/32b508ba-dc19-43cc-9324-3835ccef141d)


![0CF68E9C-0C1B-4F45-83EC-4BCC42520FDA](https://github.com/user-attachments/assets/9ebcd319-ab72-4784-aeb5-c8c377e8f870)

![567C0FA5-FCD2-484C-9379-8AF9554F1B14](https://github.com/user-attachments/assets/c5086a70-b141-4d94-8f5d-7dec2443640a)

**Comment by libukai** [comment]
好的，非常期待！

**Comment by libukai** [comment]
已经体验到了新的效果，非常感谢！
