### ISSUE TITLE
希望优先解决带图片的连续对话

### ISSUE THREAD

**Issue by muhanstudio** [flyun/chatAir#25]
目前在基础功能上，体验比较缺失的就是在支持视觉的模型上无法进行连续对话，个人感觉是一个比较严重的缺陷，希望可以优先解决一下，其他的特性功能个人觉得可以慢慢等，但是较为流畅的连续对话还是很重要的，每次都要去切换一下视觉模式，有一点割裂

**Comment by flyun** [comment]
因为要适配OpenAi、Gemini、Claude图片模型，预计本月发布图片连续对话版本

**Comment by muhanstudio** [comment]
> 因为要适配OpenAi、Gemini、Claude图片模型，预计本月发布图片连续对话版本

感谢作者，已经推荐给很多朋友用了，然后也在我用的几个中转站交流群推荐了群友用，加油🥹

**Comment by flyun** [comment]
> > 因为要适配OpenAi、Gemini、Claude图片模型，预计本月发布图片连续对话版本
> 
> 感谢作者，已经推荐给很多朋友用了，然后也在我用的几个中转站交流群推荐了群友用，加油🥹

谢谢推荐，我本身文字处理用的比较多，图片因为费率问题，就用得比较少，所以就没有支持的很完善
