### ISSUE TITLE
手机报毒

### ISSUE THREAD

**Issue by wongxg** [flyun/chatAir#26]
a gray bulimiaTGen.h

**Comment by flyun** [comment]
根据反馈以及我自己尝试，暂时只有华为系操作系统出现风险应用问题#9

初步猜测，因为ChatAir是基于Telegram二次开发应用，Telegram本身有读取联系人、短信的代码的原因造成的。但是ChatAir相关的危险权限已经删除，也不会调用无关代码，使用时也不会请求无关权限。

网上相关的误报问题
https://developer.huawei.com/consumer/cn/forum/topic/0202138980797318069
https://developer.huawei.com/consumer/cn/forum/topic/0204136738753998470

如果不放心，可以自己编译源代码，也会出现类型提示。
这个问题之后也会解决，避免给用户造成困扰。

**Comment by zxkmm** [comment]
三星手机也是相同情况。感谢大佬解答

**Comment by boris20190** [comment]
一加Google自动检测同样报危险应用, 谢谢大佬解答

**Comment by flyun** [comment]
会优先解决这个问题，先附上1.1.0版本在线apk杀毒检测报告，也可以自己测试
https://www.virustotal.com/gui/file/9719f2b10cd8394351c63f0912d1be4cea78ba353ff27fd7773cca2fde65598f/detection

如果看过代码，除了与模型api进行通信以及firebase日志收集，没有其他网络请求。也欢迎抓包、看源码。
开发ChatAir的目的之一，是想着api密钥属于私人隐私，有高危泄露风险，使用开源产品会更放心。

**Comment by flyun** [comment]
误报问题已经反馈，并且解决了。更新下手机的病毒库就不会显示误报。
