### ISSUE TITLE
Force closed when pressing `stop` button before the streaming output ends

### ISSUE THREAD

**Issue by STMRabbit** [flyun/chatAir#29]
# Reproduce:
1. Input something.
2. Press the Stop button while it is still outputting.
3. The app force closes.

**Comment by flyun** [comment]
Hello, I have followed your steps and have not reproduced the problem yet.
If possible, please provide the following information: your phone model, Android system version, which model the problem occurred on, and the approximate time when the problem occurred.

**Comment by STMRabbit** [comment]
Hello, thank you very much for response quickly! Here's some more info that might help:
phone model: Samsung galaxy S8
Android version: 9
AI model: [deepseek](https://www.deepseek.com/en)

I generated a token under my account for you to test (if it's related to the AI model)

**Comment by STMRabbit** [comment]
I generated a token under my account for you to test (if it's related to the AI model)
and I sent to your gmail address that i found inside of the app

**Comment by flyun** [comment]
Thank you. I have received your test token. Which model in deepseek did you use for testing? For example, GPT-3.5, Gemini1.5 Pro, etc. If you use a custom model, can you list the model name?

**Comment by STMRabbit** [comment]
sorry for late reply. the modal name is `deepseek-chat`

**Comment by flyun** [comment]
I have reproduced the problem, it happens occasionally, I don't know if your problem must happen. 
It will be solved soon, thanks for your reply.

**Comment by STMRabbit** [comment]
Thank you for the fixes!
It happens every time on my device tho.

**Comment by flyun** [comment]
Starting from version 1.1.0. To use deepseek, you need to turn on the old OpenAI protocol in the global AI parameters.
The old OpenAI protocol does not support the new image context, and some model vendors only adapt to the old OpenAI protocol.
