### ISSUE TITLE
Geminid安全过滤级别 设置内容过滤级别

### ISSUE THREAD

**Issue by blibilijojo** [flyun/chatAir#31]
> 希望能提供Geminid的内容过滤功能的全局默认设置。理想情况下，用户可以在软件内部的某个地方进行配置，以便所有对话都默认应用该设置。 ![image](https://private-user-images.githubusercontent.com/102420734/354981039-43aebcee-9be6-4cba-929a-fdf78100dba6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDQ2OTMsIm5iZiI6MTcyMzMwNDM5MywicGF0aCI6Ii8xMDI0MjA3MzQvMzU0OTgxMDM5LTQzYWViY2VlLTliZTYtNGNiYS05MjlhLWZkZjc4MTAwZGJhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQxNTM5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2U1NjAyNjNkOWZhMWU0MTIwOTcxMjVkYTFiYjcxN2RhMmRlMWUxNjVkNjQwNTk1Y2FmYWM5NmY1NWFhMGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VwHHoCil4Yz3e4Tfl9VEFpRHd5FBkAwwqxi1g6wPtCw)

**Comment by blibilijojo** [comment]
> 希望能提供Geminid的内容过滤功能的全局默认设置。理想情况下，用户可以在软件内部的某个地方进行配置，以便所有对话都默认应用该设置。 ![image](https://private-user-images.githubusercontent.com/102420734/354981039-43aebcee-9be6-4cba-929a-fdf78100dba6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDQ2OTMsIm5iZiI6MTcyMzMwNDM5MywicGF0aCI6Ii8xMDI0MjA3MzQvMzU0OTgxMDM5LTQzYWViY2VlLTliZTYtNGNiYS05MjlhLWZkZjc4MTAwZGJhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQxNTM5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2U1NjAyNjNkOWZhMWU0MTIwOTcxMjVkYTFiYjcxN2RhMmRlMWUxNjVkNjQwNTk1Y2FmYWM5NmY1NWFhMGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VwHHoCil4Yz3e4Tfl9VEFpRHd5FBkAwwqxi1g6wPtCw)

**Comment by flyun** [comment]
会提供一个全局关闭Gemini安全选项的功能
