### ISSUE TITLE
确实不错的项目

### ISSUE THREAD

**Issue by tiamohummer** [flyun/chatAir#33]
非常棒的开源项目，痛苦的是一个文件上万行代码。。。

**Comment by flyun** [comment]
是的，因为是二次开发Telegram。

作为全球上最为流行的聊天软件，Telegram本身业务就很复杂。加上最初的作者DrKLO编码风格，很少拆分类的逻辑，就很容易导致一个文件代码非常多。DrKLO技术扎实、代码工整、逻辑严谨，不会出现逻辑跳来跳去逻辑混乱的问题，对于这样大型的项目，我是非常佩服的。可能对于DrKLO来说上万行代码对于他来说只是几千行而已，所以没必要拆分，反而拖慢自己的效率。他甚至几乎都没有注释，十年如一日独自开发，惊为天人。

关于理解代码可以看我标的注释，限于自己的理解，可能有误，但尽量保证正确。
