### ISSUE TITLE
折叠屏竖屏状态可以隐藏左侧菜单栏

### ISSUE THREAD

**Issue by libukai** [flyun/chatAir#35]
目前在折叠屏上竖屏使用的时候，左侧的菜单栏无法自动/手动展开和收起
建议修改成类 ChatGPT 的交互方式，可以通过点击左上角的菜单按钮展开和收起

![image](https://github.com/user-attachments/assets/03efa125-6d59-451c-b2d2-e3dbf081abe6)

![image](https://github.com/user-attachments/assets/12cde79b-31ec-44e1-9074-7c78930e69db)

![image](https://github.com/user-attachments/assets/529b1aef-ab7b-450e-baca-bf7b55b451e8)

**Comment by libukai** [comment]
在另外一台设备上测试了一下，应该是对于屏幕宽度的判定问题，不知道是否能调整一下？

**Comment by flyun** [comment]
可以提供你的折叠屏型号，或者可以提供分辨率和尺寸。代码本身有针对平板的适配，估计是折叠屏被误认为平板导致的。

简单的解决办法，考虑添加一个强制手机样式的选项。

**Comment by libukai** [comment]
感谢！请帮忙看一下这个设备的情况。另外，增加开关是一个不错的想法，能一劳永逸解决问题

![CleanShot 2024-08-23 at 14 25 45@2x](https://github.com/user-attachments/assets/cc0d6d4f-5809-40f8-b3c3-4cabfaae3a72)
