### ISSUE TITLE
ollama本地不可调用

### ISSUE THREAD

**Issue by 18600709862** [flyun/chatAir#36]
手机本地安装termux,
安装ollama，启动模型，可以对话。
ollama runqwen2:1.5b
浏览器访问http://localhost:11434正常

从chatair设置
api服务器地址http://localhost:11434/v1/
全局ai参数设置自定义模型 qwen2:1.5b

对话窗口提问
报错
CLEARTEXT communication to localhost not permitted by network security policy

ollama设置了
OLLAMA_HOST=0.0.0.0:11434
OLLAMA_ORIGINS=*

不知道是哪里安全问题，需要如何设置呢

**Comment by muhanstudio** [comment]
我来帮作者回答一下，这个我之前也遇到过，实际上是因为安卓App禁止在应用内跨域直连http导致的，你需要自签一个ssl证书，使其支持https，或者自行修改代码解除限制

**Comment by 18600709862** [comment]
是手机有安全限制不能用吗
然而在浏览器直接访问http://localhost:11434/
是可以正常响应的阿
api服务器地址http://localhost:11434/v1/
手机配置https感觉是不是太复杂了

**Comment by flyun** [comment]
> 我来帮作者回答一下，这个我之前也遇到过，实际上是因为安卓App禁止在应用内跨域直连http导致的，你需要自签一个ssl证书，使其支持https，或者自行修改代码解除限制

感谢解答，确实是这样，手机端运行一些小模型还是有使用场景的。下一版会放开127.0.0.1与localhost本地请求的http限制，可能放开所有http会更好，但是不清楚会不会有什么问题，因为一些场景下，是禁止明文流量。

另外，ollama填入的api服务器地址应该是：
http://127.0.0.1:11434
或者
http://localhost:11434
程序会自动补全后缀。

下一版会优化填入的api服务器地址，比如填入http://127.0.0.1:11434 或者 http://127.0.0.1:11434/v1/chat/completions 同样生效，这样会更容易理解并且兼容更多OpenAi协议的模型提供商
