### ISSUE TITLE
HTTP 422 ERROR

### ISSUE THREAD

**Issue by LiHtCocoa** [flyun/chatAir#43]
![Screenshot_20240918_215642_info flyun chatair_edit_660878218050718](https://github.com/user-attachments/assets/38a16e41-d54f-4eac-8cad-392d488c4866)

反复出现以上问题，APIkey经过验证，地址也没有填错，在官方文档查了一下是参数错误。
如果有任何解决方法请告知，感谢🙏🏻

**Comment by flyun** [comment]
是这个问题
https://github.com/flyun/chatAir/issues/29#issuecomment-2348403547

从1.1.0版本开始。要使用deepseek，需要在全局AI参数中开启旧的OpenAI协议。
deepseek不支持OpenAI新版本协议，旧的OpenAI协议不支持新的图像上下文，所以默认为新版本协议。

**Comment by LiHtCocoa** [comment]
> 是这个问题 [#29 (comment)](https://github.com/flyun/chatAir/issues/29#issuecomment-2348403547)
> 
> 从1.1.0版本开始。要使用deepseek，需要在全局AI参数中开启旧的OpenAI协议。 deepseek不支持OpenAI新版本协议，旧的OpenAI协议不支持新的图像上下文，所以默认为新版本协议。

感谢您的回复

**Comment by m2acgi** [comment]
今天测试的，不开启旧协议，文字聊天没有这个报错，图片未测试。
