### ISSUE TITLE
可以增加python语言高亮吗

### ISSUE THREAD

**Issue by stonereese** [flyun/chatAir#9]
在tg基础上做软件，第一次见，非常棒，希望能增加python语法高亮。另外，国产手机对本程序安装包报a.gray.nebula病毒，是360加固还是类似tg的原因？

**Comment by flyun** [comment]
Python有语法高亮，如果你那边重试测试还有问题，可以贴下截图我看下。
至于显示风险应用，是Telegram的原因。因为是基于Telegram二次开发，Telegram被中国大陆手机标记为风险应用，所以chatAir也会显示。如果不放心，可以安装Telegram，也会显示同样的风险应用提示。后续会想办法修复下，因为我已经改过包名，猜测可能是通过提取其他特征判断的。

**Comment by stonereese** [comment]
感谢，因为之前主要询问arcpy相关，代码没有高亮，经测试，其他python代码可以正常高亮，应用很棒。

**Comment by flyun** [comment]
感谢使用ChatAIr，如果你使用ArcPy很多，也会做一下简单兼容可以使代码高亮

**Comment by stonereese** [comment]
> 感谢使用ChatAIr，如果你使用ArcPy很多，也会做一下简单兼容可以使代码高亮

那太感谢了～～

**Comment by flyun** [comment]
我这边测试，ArcPy可以正常代码高亮。你可以提供下询问的句子，比如：“写一些ArcPy的例子”类似这样的，我这边尝试复现下。
<img width="375" alt="ArcPy" src="https://github.com/flyun/chatAir/assets/4331063/c8f4ac18-23f5-4797-9dfc-2317ea0189b3">

**Comment by flyun** [comment]
误报问题已经反馈，并且解决了。更新下手机的病毒库就不会显示误报。
